1) importation table apprentissage et validation
2) fonction de discretisation
3) discritisation apprentissage et validation (verifier que toute les quali sont de type str)
4) arbre de classifiaction entraine sur la table d'apprentissage
5) Mesure de performance en apprentissage et en validation

In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn import preprocessing
from sklearn import metrics
from scipy.cluster.hierarchy import dendrogram, linkage, fcluster

In [41]:
import warnings
warnings.filterwarnings("ignore")

## importation table apprentissage et validation

In [42]:
#import des train_set
train_data=pd.read_table('train_set.csv',sep=",",header=0,index_col=0)
train_data.head()

assur_caravane  nbmaisons  pouvoir_achat  nbpers_au_foyer  type_client  \
cle                                                                            
1004               0          1              4                2            9   
464                0          1              3                2            7   
542                0          1              3                3            8   
4009               0          1              4                4           10   
5158               0          2              2                2            5   

      mt_auto  nb_auto  mt_incendie  nb_incendie  niv_etud_bas  ...  marie  \
cle                                                             ...          
1004        0        0            0            0             8  ...      7   
464         6        1            0            0             3  ...      4   
542         6        1            0            0             8  ...      9   
4009        0        0            0            0             9  ...      5   
5158        6        1            2            1             3  ...      2   

      autre_relation  assur_sante_prive  assur_sante_public  mt_RC_entreprise  \
cle                                                                             
1004               2                  1                   8                 0   
464                2                  2                   7                 0   
542                0                  2                   7                 0   
4009               4                  0                   9                 0   
5158               3                  0                   9                 0   

      nb_RC_entreprise  mt_camion_livraison  nb_camion_livraison  nb_remorque  \
cle                                                                             
1004                 0                    0                    0            0   
464                  0                    0                    0            0   
542                  0                    0                    0            0   
4009                 0                    0                    0            0   
5158                 0                    0                    0            0   

      mt_remorque  
cle                
1004            0  
464             0  
542             0  
4009            0  
5158            0  

[5 rows x 32 columns]

In [43]:
#import des test_set
test_data=pd.read_table('test_set.csv',sep=",",header=0,index_col=0)
test_data.head()

assur_caravane  nbmaisons  pouvoir_achat  nbpers_au_foyer  type_client  \
cle                                                                            
841                0          1              1                1            6   
3339               0          1              1                4            7   
2977               0          1              4                3            3   
5115               0          1              4                3            3   
528                0          1              1                2            7   

      mt_auto  nb_auto  mt_incendie  nb_incendie  niv_etud_bas  ...  marie  \
cle                                                             ...          
841         0        0            2            1             5  ...      3   
3339        6        1            0            0             9  ...      5   
2977        5        1            3            1             7  ...      8   
5115        6        1            0            0             3  ...      6   
528         6        1            0            0             2  ...      9   

      autre_relation  assur_sante_prive  assur_sante_public  mt_RC_entreprise  \
cle                                                                             
841                5                  0                   9                 0   
3339               4                  2                   7                 0   
2977               1                  0                   9                 0   
5115               2                  2                   7                 0   
528                0                  2                   7                 0   

      nb_RC_entreprise  mt_camion_livraison  nb_camion_livraison  nb_remorque  \
cle                                                                             
841                  0                    0                    0            0   
3339                 0                    0                    0            0   
2977                 0                    0                    0            0   
5115                 0                    0                    0            0   
528                  0                    0                    0            0   

      mt_remorque  
cle                
841             0  
3339            0  
2977            0  
5115            0  
528             0  

[5 rows x 32 columns]

In [44]:
test_data

assur_caravane  nbmaisons  pouvoir_achat  nbpers_au_foyer  type_client  \
cle                                                                            
841                0          1              1                1            6   
3339               0          1              1                4            7   
2977               0          1              4                3            3   
5115               0          1              4                3            3   
528                0          1              1                2            7   
...              ...        ...            ...              ...          ...   
492                0          1              8                3            2   
193                0          1              1                2            7   
5581               0          1              2                2            4   
4408               0          1              4                2           10   
3697               0          1              3                4            8   

      mt_auto  nb_auto  mt_incendie  nb_incendie  niv_etud_bas  ...  marie  \
cle                                                             ...          
841         0        0            2            1             5  ...      3   
3339        6        1            0            0             9  ...      5   
2977        5        1            3            1             7  ...      8   
5115        6        1            0            0             3  ...      6   
528         6        1            0            0             2  ...      9   
...       ...      ...          ...          ...           ...  ...    ...   
492         0        0            0            0             5  ...      3   
193         6        1            0            0             9  ...      9   
5581        0        0            0            0             0  ...      0   
4408        6        1            6            1             6  ...      5   
3697        0        0            6            1             6  ...      8   

      autre_relation  assur_sante_prive  assur_sante_public  mt_RC_entreprise  \
cle                                                                             
841                5                  0                   9                 0   
3339               4                  2                   7                 0   
2977               1                  0                   9                 0   
5115               2                  2                   7                 0   
528                0                  2                   7                 0   
...              ...                ...                 ...               ...   
492                2                  2                   7                 0   
193                0                  0                   9                 0   
5581               7                  6                   3                 0   
4408               4                  2                   7                 2   
3697               1                  2                   7                 0   

      nb_RC_entreprise  mt_camion_livraison  nb_camion_livraison  nb_remorque  \
cle                                                                             
841                  0                    0                    0            0   
3339                 0                    0                    0            0   
2977                 0                    0                    0            0   
5115                 0                    0                    0            0   
528                  0                    0                    0            0   
...                ...                  ...                  ...          ...   
492                  0                    0                    0            0   
193                  0                    0                    0            1   
5581                 0                    0                    0            0   
4408 

In [45]:
liste_des_variables=[
 'pouvoir_achat',
 'niv_etud_bas',
 'niv_etude_haut',
 'revenu1',
 'locataire',
 'marie',
 'revenu3',
 'assur_caravane']
variables_quanti=list(set(liste_des_variables)-set(["assur_caravane"]))

In [46]:
train_data[liste_des_variables]

pouvoir_achat  niv_etud_bas  niv_etude_haut  revenu1  locataire  marie  \
cle                                                                            
1004              4             8               1        0          3      7   
464               3             3               1        4          5      4   
542               3             8               1        3          3      9   
4009              4             9               0        2          4      5   
5158              2             3               2        5          5      2   
...             ...           ...             ...      ...        ...    ...   
4932              7             4               4        1          1      6   
3265              4             4               1        3          9      4   
1654              4             9               0        9          5      5   
2608              5             5               0        0          0      9   
2733              7             0               3        0          0      7   

      revenu3  assur_caravane  
cle                            
1004        2               0  
464         2               0  
542         2               0  
4009        2               0  
5158        2               0  
...       ...             ...  
4932        3               0  
3265        4               0  
1654        0               0  
2608        9               1  
2733        5               0  

[4657 rows x 8 columns]

## Oversampling

In [47]:
def oversampling(donnees,nom_var):
    data=donnees.copy()
    indexval1=data.index[data[nom_var]==1]
    indexval0=data.index[data[nom_var]==0]
    #tirage aléatoire avec remise des valeurs du groupe 1
    newliste=np.random.choice(indexval1,indexval0.shape[0],replace=True).astype('int32')
    newliste1=[]
    for val in newliste:
        newliste1.append(np.min(np.where(data.index==val)))
    data_over=data.take(newliste1)
    data_over=pd.concat([data_over,data.loc[indexval0]],axis=0)
    return(data_over)


train_set_over = oversampling(train_data[liste_des_variables],'assur_caravane')#initialisation et choix pour replacement qui permet de spécifier
test_set_over = oversampling(test_data[liste_des_variables],'assur_caravane')#initialisation et choix pour replacement qui permet de spécifier



X_train_over=train_set_over[variables_quanti] 
X_test_over=test_set_over[variables_quanti]

y_train_over=train_set_over['assur_caravane']
y_test_over=test_set_over['assur_caravane']

## **KNN** :

In [87]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(train_set_over.drop(["assur_caravane"],axis=1))

X_train_cr = scaler.transform(X_train_over)
X_test_cr = scaler.transform(X_test_over)

df_train_cr=pd.concat([pd.DataFrame(X_train_cr,index=X_train_over.index),y_train_over],axis=1)
df_test_cr=pd.concat([pd.DataFrame(X_test_cr,X_test_over.index),y_test_over],axis=1)

X_train_over=df_train_cr.iloc[:,0:7]
X_test_over=df_test_cr.iloc[:,0:7]

y_train_over=df_train_cr['assur_caravane']
y_test_over=df_test_cr['assur_caravane']

In [88]:
from sklearn.metrics import confusion_matrix, classification_report

In [89]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

y_train=y_train_over
y_test=y_test_over

k=20
knn=KNeighborsClassifier(n_neighbors=k).fit(X_train_over,y_train_over)
y_predict=knn.predict(X_train_over)
y_predict_test1=knn.predict(X_test_over)


print("KNN pour K=",k)
#calcule de précision-entrainnement
print("calcule de précision-entrainnement : ", knn.score(X_train_over, y_train_over))
#calcule de prediction-test
print("calcule de précision-test : ", knn.score(X_test_over, y_test))

print("\nMatrice de confusion avec LISTE train-validation :")
print(confusion_matrix(y_train,y_predict))

print("\nMatrice de confusion avec LISTE test-validation :")
print(confusion_matrix(y_test,y_predict_test1))

print(classification_report(y_test_over,y_predict_test1))

KNN pour K= 20
calcule de précision-entrainnement :  0.8023255813953488
calcule de précision-test :  0.5652573529411765

Matrice de confusion avec LISTE train-validation :
[[2751 1635]
 [  99 4287]]

Matrice de confusion avec LISTE test-validation :
[[656 432]
 [514 574]]
              precision    recall  f1-score   support

           0       0.56      0.60      0.58      1088
           1       0.57      0.53      0.55      1088

    accuracy                           0.57      2176
   macro avg       0.57      0.57      0.56      2176
weighted avg       0.57      0.57      0.56      2176



# Bagging

In [81]:
B=1000
n=train_set_over.shape[0]

In [82]:
X1=df_train_cr.sample(n,replace=True)
X2=df_train_cr.sample(n,replace=True)
X3=df_train_cr.sample(n,replace=True)
X4=df_train_cr.sample(n,replace=True)
X5=df_train_cr.sample(n,replace=True)


X_train1=X1.drop(["assur_caravane"],axis=1)
y_train1=X1['assur_caravane']

X_train2=X2.drop(["assur_caravane"],axis=1)
y_train2=X2['assur_caravane']

X_train3=X3.drop(["assur_caravane"],axis=1)
y_train3=X3['assur_caravane']

X_train4=X4.drop(["assur_caravane"],axis=1)
y_train4=X4['assur_caravane']

X_train5=X5.drop(["assur_caravane"],axis=1)
y_train5=X5['assur_caravane']

In [83]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

y_train=y_train1
y_test=y_test_over

knn1=KNeighborsClassifier(n_neighbors=k).fit(X_train1,y_train1)
y_predict=knn1.predict(X_train1)
y_predict_test1=knn1.predict(X_test_over)

c=1

print("KNN1 pour K=",k)
#calcule de précision-entrainnement
print("calcule de précision-entrainnement : ", knn1.score(X_train1, y_train1))
#calcule de prediction-test
print("calcule de précision-test : ", knn1.score(X_test_over, y_test))

print("\nMatrice de confusion avec LISTE",c," train-validation :")
print(confusion_matrix(y_train,y_predict))

print("\nMatrice de confusion avec LISTE",c," test-validation :")
print(confusion_matrix(y_test,y_predict_test1))

print(classification_report(y_test_over,y_predict_test1))

KNN1 pour K= 20
calcule de précision-entrainnement :  0.8235294117647058
calcule de précision-test :  0.5873161764705882

Matrice de confusion avec LISTE 1  train-validation :
[[3074 1329]
 [ 219 4150]]

Matrice de confusion avec LISTE 1  test-validation :
[[707 381]
 [517 571]]
              precision    recall  f1-score   support

           0       0.58      0.65      0.61      1088
           1       0.60      0.52      0.56      1088

    accuracy                           0.59      2176
   macro avg       0.59      0.59      0.59      2176
weighted avg       0.59      0.59      0.59      2176



In [85]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix


y_train=y_train2
y_test=y_test_over

knn2=KNeighborsClassifier(n_neighbors=k).fit(X_train2,y_train2)
y_predict=knn2.predict(X_train2)
y_predict_test2=knn2.predict(X_test_over)


c=2
print("KNN2 pour K=",k)
#calcule de précision-entrainnement
print("calcule de précision-entrainnement : ", knn2.score(X_train2, y_train2))
#calcule de prediction-test
print("calcule de précision-test : ", knn2.score(X_test_over, y_test))

print("\nMatrice de confusion avec LISTE",c," train-validation :")
print(confusion_matrix(y_train,y_predict))

print("\nMatrice de confusion avec LISTE",c," test-validation :")
print(confusion_matrix(y_test,y_predict_test2))

print(classification_report(y_test_over,y_predict_test2))

KNN2 pour K= 40
calcule de précision-entrainnement :  0.743844049247606
calcule de précision-test :  0.5657169117647058

Matrice de confusion avec LISTE 2  train-validation :
[[2904 1512]
 [ 735 3621]]

Matrice de confusion avec LISTE 2  test-validation :
[[644 444]
 [501 587]]
              precision    recall  f1-score   support

           0       0.56      0.59      0.58      1088
           1       0.57      0.54      0.55      1088

    accuracy                           0.57      2176
   macro avg       0.57      0.57      0.57      2176
weighted avg       0.57      0.57      0.57      2176



In [86]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

y_train=y_train3
y_test=y_test_over

knn3=KNeighborsClassifier(n_neighbors=k).fit(X_train3,y_train3)
y_predict=knn3.predict(X_train3)
y_predict_test3=knn3.predict(X_test_over)

c=3
print("KNN3 pour K=",k)
#calcule de précision-entrainnement
print("calcule de précision-entrainnement : ", knn3.score(X_train3, y_train3))
#calcule de prediction-test
print("calcule de précision-test : ", knn3.score(X_test_over, y_test))

print("\nMatrice de confusion avec LISTE",c," train-validation :")
print(confusion_matrix(y_train,y_predict))

print("\nMatrice de confusion avec LISTE",c," test-validation :")
print(confusion_matrix(y_test,y_predict_test3))

print(classification_report(y_test_over,y_predict_test3))

KNN3 pour K= 40
calcule de précision-entrainnement :  0.7370041039671683
calcule de précision-test :  0.5615808823529411

Matrice de confusion avec LISTE 3  train-validation :
[[2879 1507]
 [ 800 3586]]

Matrice de confusion avec LISTE 3  test-validation :
[[684 404]
 [550 538]]
              precision    recall  f1-score   support

           0       0.55      0.63      0.59      1088
           1       0.57      0.49      0.53      1088

    accuracy                           0.56      2176
   macro avg       0.56      0.56      0.56      2176
weighted avg       0.56      0.56      0.56      2176



In [74]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

y_train=y_train4
y_test=y_test_over

k=40
knn4=KNeighborsClassifier(n_neighbors=k).fit(X_train4,y_train4)
y_predict=knn4.predict(X_train4)
y_predict_test4=knn4.predict(X_test_over)

c=4
print("KNN4 pour K=",k)
#calcule de précision-entrainnement
print("calcule de précision-entrainnement : ", knn4.score(X_train4, y_train4))
#calcule de prediction-test
print("calcule de précision-test : ", knn4.score(X_test_over, y_test))

print("\nMatrice de confusion avec LISTE",c," train-validation :")
print(confusion_matrix(y_train,y_predict))

print("\nMatrice de confusion avec LISTE",c," test-validation :")
print(confusion_matrix(y_test,y_predict_test4))

print(classification_report(y_test_over,y_predict_test4))

KNN4 pour K= 40
calcule de précision-entrainnement :  0.7317601459188326
calcule de précision-test :  0.5661764705882353

Matrice de confusion avec LISTE 4  train-validation :
[[2792 1597]
 [ 756 3627]]

Matrice de confusion avec LISTE 4  test-validation :
[[653 435]
 [509 579]]
              precision    recall  f1-score   support

           0       0.56      0.60      0.58      1088
           1       0.57      0.53      0.55      1088

    accuracy                           0.57      2176
   macro avg       0.57      0.57      0.57      2176
weighted avg       0.57      0.57      0.57      2176



In [75]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix

y_train=y_train5
y_test=y_test_over

knn5=KNeighborsClassifier(n_neighbors=k).fit(X_train5,y_train5)
y_predict=knn5.predict(X_train5)
y_predict_test5=knn5.predict(X_test_over)

c=5
print("KNN5 pour K=",k)
#calcule de précision-entrainnement
print("calcule de précision-entrainnement : ", knn5.score(X_train5, y_train5))
#calcule de prediction-test
print("calcule de précision-test : ", knn5.score(X_test_over, y_test))

print("\nMatrice de confusion avec LISTE",c," train-validation :")
print(confusion_matrix(y_train,y_predict))

print("\nMatrice de confusion avec LISTE",c," test-validation :")
print(confusion_matrix(y_test,y_predict_test5))

print(classification_report(y_test_over,y_predict_test5))

KNN5 pour K= 40
calcule de précision-entrainnement :  0.7341541267669859
calcule de précision-test :  0.5716911764705882

Matrice de confusion avec LISTE 5  train-validation :
[[2916 1556]
 [ 776 3524]]

Matrice de confusion avec LISTE 5  test-validation :
[[657 431]
 [501 587]]
              precision    recall  f1-score   support

           0       0.57      0.60      0.59      1088
           1       0.58      0.54      0.56      1088

    accuracy                           0.57      2176
   macro avg       0.57      0.57      0.57      2176
weighted avg       0.57      0.57      0.57      2176



### Methode du vote (Pour la classification):

In [78]:
def methode_vote(l):
    n=len(l)
    L=[]
    for i in range(len(l[0,:])):
        res=0
        for valeur in l[:,i]:
            res+=int(valeur)
        res=res/n
        if res>=0.5 :
            L.append(1)
        else :
            L.append(0)
    return L

l=np.array([y_predict_test1,y_predict_test2,y_predict_test3,y_predict_test4,y_predict_test5])
y_pred=methode_vote(l)

In [79]:
#calcule de prediction-test
def score(y,y_pred):
    res=0
    for i in range(len(y)):
        if (y[i]==y_pred[i]):
            res+=1
    res=res/len(y)
    return res

resultats_class=classification_report(y_test_over,y_pred)
print("calcule de précision-test : ", (0.52+0.63)/2)
print(resultats_class)

calcule de précision-test :  0.575
              precision    recall  f1-score   support

           0       0.56      0.61      0.58      1088
           1       0.57      0.52      0.54      1088

    accuracy                           0.56      2176
   macro avg       0.56      0.56      0.56      2176
weighted avg       0.56      0.56      0.56      2176

